<?xml version="1.0" encoding="ISO-8859-1"?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
		
	<xsl:output method="xml" version="1.0" encoding="ISO-8859-1"
		indent="yes" cdata-section-elements="details summary steps expectedresults" />
	<xsl:template match="/">
		<xsl:variable name="featureId" select="testSuite/testCases/testCase/featureId" />
		<requirements>
			<xsl:for-each select="testSuite/rtmRequirements/rtmRequirement">
				<requirement>
					<docid><![CDATA[]]><xsl:value-of select="substring-after(requirement, 'REQ - ')"/><![CDATA[]]></docid>
					<title><xsl:value-of select="requirement" /><![CDATA[, Feature ]]>  <xsl:value-of select="$featureId" /><![CDATA[]]></title>
					<description><![CDATA[Requirements Document automatic generated by TaRGeT.]]></description>
				</requirement>
			</xsl:for-each>
		</requirements>
	</xsl:template>
</xsl:stylesheet>